CREATE TABLE IF NOT EXISTS imovel (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipoimovel VARCHAR(50) NOT NULL,
    finalidade VARCHAR(50) NOT NULL,
    endereco VARCHAR(300) NOT NULL,
    cidade VARCHAR(150) NOT NULL,
    area INT NOT NULL,
    valor DOUBLE NOT NULL
    );

INSERT INTO imovel (tipoimovel, finalidade, endereco, cidade, area, valor)
VALUES ('Casa', 'Aluguel', 'Rua Maria das Flores',
        'São Paulo', '40', '4000.00');